# Generated by Django 6.1.1 on 2026-09-08 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apoderados',
            fields=[
                ('id_apoderado', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('parentesco', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Apoderados',
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_email', models.CharField(max_length=100)),
                ('accion', models.CharField(max_length=100)),
                ('tabla_afectada', models.CharField(blank=True, max_length=50, null=True)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Bitacora',
            },
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(blank=True, max_length=50, null=True)),
                ('curso', models.CharField(max_length=20)),
                ('email_apoderado', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_qr', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('stock_actual', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=0)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('rol', models.CharField(default='administrativo', max_length=30)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='MovimientosStock',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
                ('stock_antes', models.IntegerField()),
                ('stock_despues', models.IntegerField()),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('usuario_responsable', models.CharField(max_length=100)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='gestion.productos')),
            ],
            options={
                'db_table': 'MovimientosStock',
            },
        ),
        migrations.CreateModel(
            name='EstudianteApoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_principal', models.BooleanField(default=False)),
                ('id_apoderado', models.ForeignKey(db_column='id_apoderado', on_delete=django.db.models.deletion.CASCADE, to='gestion.apoderados')),
                ('id_estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.CASCADE, to='gestion.estudiantes')),
            ],
            options={
                'db_table': 'EstudianteApoderado',
                'unique_together': {('id_estudiante', 'id_apoderado')},
            },
        ),
        migrations.CreateModel(
            name='Atrasos',
            fields=[
                ('id_atraso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('minutos_atraso', models.IntegerField()),
                ('justificado', models.BooleanField(default=False)),
                ('notificado_apoderado', models.BooleanField(default=False)),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('id_estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.CASCADE, to='gestion.estudiantes')),
            ],
            options={
                'db_table': 'Atrasos',
                'unique_together': {('id_estudiante', 'fecha')},
            },
        ),
    ]
